name: Emergency
version: '${project.version}'
main: io.github.cy3902.emergency.Emergency
api-version: 1.19
softdepend: [MythicMobs,PlaceholderAPI]

commands:
  emergency:
    description: Handles emergency commands
    permission: emergency.use

permissions:
  emergency.use:
    description: Allows use of the emergency command
    default: op